name: test
run-name: Running tests for ${{ github.ref }}
on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
    workflow_call:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version-file: ./.nvmrc
                  cache: npm

            - name: Install NPM Packages
              run: npm ci

            - name: Generate Test Data
              run: npm run test:generate-data

            - name: Run Tests & Publish Coverage to Code Climate
              uses: paambaati/codeclimate-action@v4.0.0
              env:
                  CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
              with:
                  coverageCommand: npm run test:cov
